import java.io.*;

import org.w3c.dom.*;

import javax.xml.parsers.*;

import javax.xml.transform.*;
import javax.xml.transform.dom.*;
import javax.xml.transform.stream.*;

public class DomToXML
{
    /**
     * Our goal is to create a DOM XML tree and then print the XML.
     */
    public static void main (String args[])
    {
        new DomToXML();
    }

    public DomToXML()
    {
        try
        {
            //// Creating an empty XML Document

            // We need a Document
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            DocumentBuilder docBuilder = dbf.newDocumentBuilder();
            Document doc = docBuilder.newDocument();

            //// Creating the XML tree

            // Create the root element and add it to the document
            Element root = doc.createElement("root");
            doc.appendChild(root);

            // Create a comment and put it in the root element
            Comment comment = doc.createComment(" This XML is generated by Java! ");
            root.appendChild(comment);

            // Create child element, add an attribute, and add to root
            Element child = doc.createElement("child");
            child.setAttribute("name", "value");
            root.appendChild(child);

            Element subChild = doc.createElement("grand-child");
            subChild.setAttribute("patron", "Gates");
            child.appendChild(subChild);

            // Add a text element to the child
            Text text = doc.createTextNode("Some text\nMultiline...");
            child.appendChild(text);

            //// Output the XML

            // Set up a transformer
            TransformerFactory tf = TransformerFactory.newInstance();
            Transformer trans = tf.newTransformer();
            trans.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
            trans.setOutputProperty(OutputKeys.DOCTYPE_SYSTEM, "users.dtd");
            trans.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "yes");
            trans.setOutputProperty(OutputKeys.INDENT, "yes");

            // Create string from XML tree
            StringWriter sw = new StringWriter();
            StreamResult result = new StreamResult(sw);
            DOMSource source = new DOMSource(doc);
            trans.transform(source, result);
            String xmlString = sw.toString();

            // Print XML
            System.out.println("Generated XML:\n\n" + xmlString);
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
    }
}
